# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ee2b0d151a35466d6a139c196890d56e4ec24d62755376a0ad6df99cc3c7a3c65e6624474ab4fb79ed477ffae976090272e8109c45188e337dbe0ed20381e6d

test:
  secret_key_base: c4037e17d16d95ef78f9e499190cafc08c2d2c9ceab303b73e68644f1700dd73dfe98cfae9f7d40802a8168296e85a5517d3870e1d6a119194b06e598c174f5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
